apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: todo
          env:
            - name: TODO_DEV
              value: "true"
