apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: todo-app-skaffold
build:
  artifacts:
    - image: todo
      docker:
        dockerfile: services/todo/Dockerfile
      sync:
        infer: []
    - image: goose
      docker:
        dockerfile: cmd/goose/Dockerfile
    - image: apidoc
      docker:
        dockerfile: api/Dockerfile
      sync:
        manual:
          - src: api/api.yaml
            dest: /usr/share/nginx/html/api.yaml
deploy:
  statusCheckDeadlineSeconds: 300
profiles:
  - name: local
    activation:
      - kubeContext: kind-local
      - command: dev
      - command: run
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: services/todo/Dockerfile.dev
    deploy:
      kubeContext: kind-local
      kustomize:
        paths:
          - ops/overlays/dev
    portForward:
      - resourceType: service
        resourceName: todo
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: apidoc
        port: 80
        localPort: 9000
      - resourceType: service
        resourceName: postgres
        port: 5432
