apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: todo-app-skaffold
build:
  artifacts:
    - image: goose
      docker:
        dockerfile: cmd/goose/Dockerfile
    - image: todo
      docker:
        dockerfile: services/todo/Dockerfile
    - image: redoc
      docker:
        dockerfile: api/Dockerfile
deploy:
  statusCheckDeadlineSeconds: 300
profiles:
  - name: local
    activation:
      - kubeContext: kind-local
      - command: dev
      - command: run
    deploy:
      kustomize:
        paths:
          - ops/overlays/dev
      kubeContext: kind-local
    portForward:
      - resourceType: service
        resourceName: todo
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: redoc
        port: 80
        localPort: 9000
      - resourceType: service
        resourceName: postgres
        port: 5432
  - name: bootstrap
    deploy:
      kustomize:
        paths:
          - ops/bootstrap/overlays/dev
      kubeContext: kind-local
