apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: todo-app-skaffold

.common: &common
  namespace: todo

build:
  artifacts:
    - image: todo/api
      docker:
        dockerfile: services/todo/Dockerfile
      sync:
        infer: []
    - image: todo/migration
      docker:
        dockerfile: cmd/goose/Dockerfile
    - image: todo/apidoc
      docker:
        dockerfile: api/Dockerfile
  local:
    useBuildkit: true
deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: todo
        <<: *common
        createNamespace: true
        chartPath: ops/charts/api
        useHelmSecrets: true
        artifactOverrides:
          image: todo/api

portForward:
  - resourceType: service
    resourceName: todo
    <<: *common
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: apidoc
    <<: *common
    port: 80
    localPort: 9000
  - resourceType: service
    resourceName: postgres
    <<: *common
    port: 5432

profiles:
  - name: local
    activation:
      - command: dev
      - command: debug
    deploy:
      kubeContext: kind-local

  - name: remote
    activation:
      - command: run
      - command: deploy
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value: []

  - name: build-dev
    activation:
      - command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: services/todo/Dockerfile.dev
