apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todo
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
    - host: some_host
      http:
        paths:
          - path: /
            backend:
              serviceName: apidoc
              servicePort: 80
          - path: /api/v1/todo
            backend:
              serviceName: todo
              servicePort: 80
