name: Skaffold Todo App
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go:
          - "1.15"
          - "1.14"
    name: Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Lint
        run: make lint
      - name: Unit test with coverage
        run: make test-coverage
      - name: Integration test
        run: make test-integration
